#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/drew/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# Authentication agent for privilege escalation
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Notification daemon
dunst -config ~/.fluxbox/dunst/dunstrc &

# Compositor for transparency and effects
picom --config ~/.fluxbox/picom/picom.conf --animations -b &

# wallpaper 
feh --bg-fill ~/.fluxbox/wallpaper/wallhaven-5g2zr9_3440x1440.png &

# Workspace pager - commented out, use Super+P to toggle
# fbpager -rc ~/.fluxbox/fbpager/fbpager.config &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/drew/.fluxbox/log"
